# -*- coding: utf-8 -*-
"""02_double_list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J71eIKHOUOqLzQA9roQ31_b3WGw9mWNm
"""

def main():
  number = [1,2,3,4,5]

  for i in range(len(number)):
    index_end = number[i]
    number[i] = index_end * 2

  print(number)



if __name__ == '__main__':
    main()