# -*- coding: utf-8 -*-
"""03_erase_canvas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f06EzXKyYDrY6_T08Zuihk1nI9CEQk4j
"""

import tkinter as tk  # Tkinter ka istemal GUI (Graphical User Interface) banane ke liye hota hai

# Canvas aur grid ke liye settings
CANVAS_WIDTH = 400   # Canvas ki width (chowrāi)
CANVAS_HEIGHT = 400  # Canvas ki height (lambāi)
CELL_SIZE = 40       # Har cell ka size (ek square)
ERASER_SIZE = 20     # Eraser ka size (chhota rectangle jo erase karega)

class EraserApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Eraser on Grid")  # Window ka title set karte hain

        # Canvas create karte hain jisme hum apni grid draw karenge
        self.canvas = tk.Canvas(root, width=CANVAS_WIDTH, height=CANVAS_HEIGHT, bg="white")
        self.canvas.pack()

        # Ek dictionary banate hain taake har cell ka reference store kar sakein
        self.cells = {}

        # Grid draw karne ka loop
        for row in range(CANVAS_HEIGHT // CELL_SIZE):  # Rows ka loop
            for col in range(CANVAS_WIDTH // CELL_SIZE):  # Columns ka loop
                x1 = col * CELL_SIZE  # Rectangle ka left x-coordinate
                y1 = row * CELL_SIZE  # Rectangle ka top y-coordinate
                x2 = x1 + CELL_SIZE   # Rectangle ka right x-coordinate
                y2 = y1 + CELL_SIZE   # Rectangle ka bottom y-coordinate

                # Ek blue rectangle create karte hain jo grid ka ek cell hoga
                rect = self.canvas.create_rectangle(x1, y1, x2, y2, fill="blue", outline="black")

                # Har rectangle (cell) ko dictionary mai store karte hain
                self.cells[(col, row)] = rect

        # Eraser ko create karte hain (initial position (0,0) hai)
        self.eraser = self.canvas.create_rectangle(0, 0, ERASER_SIZE, ERASER_SIZE, fill="pink", outline="red")

        # Mouse ki har movement ke saath erase_objects function run karein
        self.canvas.bind("<Motion>", self.erase_objects)

    def erase_objects(self, event):
        """Yeh function eraser ko move karta hai aur blue cells ko white karta hai"""
        x, y = event.x, event.y  # Mouse ka x, y position lete hain

        # Eraser ko mouse ke saath move karte hain
        self.canvas.coords(self.eraser, x, y, x + ERASER_SIZE, y + ERASER_SIZE)

        # Check karte hain ke eraser kisi cell ke upar hai ya nahi
        for (col, row), rect in self.cells.items():
            x1, y1, x2, y2 = self.canvas.coords(rect)  # Har rectangle ka position lete hain

            # Agar eraser kisi rectangle ko touch kare, to uska color white kar dein
            if x1 < x < x2 and y1 < y < y2:
                self.canvas.itemconfig(rect, fill="white")

# Application ko run karte hain
if __name__ == "__main__":
    root = tk.Tk()
    app = EraserApp(root)
    root.mainloop()  # Tkinter ka loop jo application ko chalata rahega