# -*- coding: utf-8 -*-
"""04_flowing_with_data_structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNs2S0Gox82NCYXP5nEETMmlj_CdQZtE
"""

def add_three_copies(my_list, data):
  for i in range(3):
    my_list.append(data)


def main():
    message = input("Enter a message to copy: \033[1;3m")

    my_list = []
    print(f"\033[0mList before: {my_list}")
    add_three_copies(my_list, message)
    print(f"List after: {my_list}")




if __name__ == '__main__':
    main()