# -*- coding: utf-8 -*-
"""02_international_voting_age.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qnBBxHoRcQUrDkz5pewlponHw8w2zhg
"""

CBLUE = '\33[34m'
CWHITE = '\33[37m'

def main():
    Peturksbouipo_age = 16
    Stanlau_age = 25
    Mayengua_age = 48

    user_input = int(input(f"How old are you? {CBLUE}"))

    if(user_input >= Peturksbouipo_age):
      print(f"{CWHITE}You can vote in Peturksbouipo where the voting age is {Peturksbouipo_age}.")
    else:
      print(f"{CWHITE}You cannot vote in Peturksbouipo where the voting age is {Peturksbouipo_age}.")


    if(user_input >= Stanlau_age):
      print(f"{CWHITE}You can vote in Stanlau where the voting age is {Stanlau_age}.")
    else:
      print(f"{CWHITE}You cannot vote in Stanlau where the voting age is {Stanlau_age}.")

    if(user_input >= Mayengua_age):
      print(f"{CWHITE}You can vote in Mayengua where the voting age is {Mayengua_age}.")
    else:
      print(f"{CWHITE}You cannot vote in Mayengua where the voting age is {Mayengua_age}.")

if __name__ == '__main__':
    main()