# -*- coding: utf-8 -*-
"""05_random_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vi8mCy8dTnekT4yuFnKgD0Uh2kJDgSVs
"""

import random

N_NUMBERS : int = 10
MIN_VALUE : int = 1
MAX_VALUE : int = 100

def main():



    for _ in range(N_NUMBERS):
      number = random.randint(MIN_VALUE, MAX_VALUE)

      print(f"{number}", end=" ")


if __name__ == '__main__':
    main()