# -*- coding: utf-8 -*-
"""01_add_two_numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7FKutz7cLmLoZhmZq4uhtTDUjoCuFuV
"""

def main():
    print("This program adds two numbers.")
    # user input first number
    firstNumber : str = input("Enter first number: ")
    # (firstNumber) convert to INT
    firstNumber : int = int(firstNumber)

    # user input second number
    secondNumber  : str = input("Enter second number: ")

    # (secondNumber) convert to INT
    secondNumber : int = int(secondNumber)

    # (firstNumber + secondNumber) sum two number2
    total : int = firstNumber + secondNumber

    # print the total number and display the terminal
    print("The total is " + str(total) + ".")


# This provided line is required at the end of
# Python file to call the main() function.
if __name__ == '__main__':
    main()

