# -*- coding: utf-8 -*-
"""02_agreement_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCei8CTLul_k2hT-J1uBssAH_iQacRwE
"""

def main():

    favorite_animal = input("What's your favorite animal?\033[1;3m")

    print(f"\033[0mMy favorite animal is also {favorite_animal}!")




# This provided line is required at the end of
# Python file to call the main() function.
if __name__ == '__main__':
    main()