# -*- coding: utf-8 -*-
"""06_square_number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMUlDX1wPzYcX5zkZA6sIdQSbEJ_Z1po
"""

def main():
    num: float = float(input("Type a number to see its square: \033[1;3m")) # Make sure to cast the input to a float so we can do math with it!
    print("\033[0m"+ str(num) + " squared is " + str(num ** 2)) # num * num is equivalent to num ** 2. The ** operator raises something to a power!


# There is no need to edit code beyond this point

if __name__ == '__main__':
    main()