# -*- coding: utf-8 -*-
"""02_e=mc2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcH2hTLjSPkP2ghn7Gu9KvajwHTK9F8P
"""

C: int = 299792458  # Speed of light in meters per second

def main():

    # User se input le raha hu (mass in kg)
    mass_in_kg: float = float(input("Enter kilos of mass: \033[1;3m"))


    # Energy calculate kar raha hu using formula E = mc²
    energy_in_joules: float = mass_in_kg * (C ** 2)


    # Calculation steps aur result show kar raha hu

    print("\033[0me = m * C^2...") # Formula show kar raha hu
    print("\033[0mm = " + str(mass_in_kg) + " kg") # User ka diya hua mass show kar raha hu
    print("\033[0mC = " + str(C) + " m/s") # Speed of light show kar raha hu

     # Calculate ki gayi energy show kar raha hu (joules me)

    print("\033[0m",str(energy_in_joules) + " joules of energy!")


# There is no need to edit code beyond this point

if __name__ == '__main__':
    main()

