# -*- coding: utf-8 -*-
"""05_remainder_division.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kO9RjCH3wrIzrsipx_M8NUq2caLhoJCN
"""

def main():
  # User se ek integer input le raha hu jo divide hoga
  dividing: int = int(input("Please enter an integer to be divided: \033[1;3m"))
  # User se ek integer input le raha hu jo divisor hoga
  divisor: int = int(input("Please enter an integer to divide by: \033[1;3m"))

  # Quotient nikal raha hu (dividing ko divisor se divide kar ke)
  quotient: int = dividing // divisor

  # Remainder nikal raha hu (dividing ka divisor se bachne wala hissa)
  remainder: int = dividing % divisor

  # Result ko print kar raha hu
  print("\033[0mThe result of this division is " + str(quotient) + " with a remainder of " + str(remainder))

if __name__ == '__main__':
    main()