# -*- coding: utf-8 -*-
"""06_rolldice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kAciBzNhvfRQ1FpMczsHZ-Ld4mF_PbIq
"""

def main():
    import random

    NUM_SIDES: int = 6

    die1: int = random.randrange(1, NUM_SIDES + 1)
    die2: int = random.randrange(1, NUM_SIDES + 1)

    total = die1 + die2

    print(f"Dice have {NUM_SIDES} sides each.")
    print(f"First Dice No {die1}")
    print(f"Second Dice No {die2}")
    print(f"Your total is {total}.")


if __name__ == '__main__':
    main()