# -*- coding: utf-8 -*-
"""07_seconds_in_year.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12V2Zd7Fo7LmMQw71KJDonKjPi8nBaBBI
"""

Days = 365
hours = 24
minutes = 60
seconds = 60

def main():
  print(f"There are {Days * hours * minutes * seconds} seconds in a year!")




if __name__ == '__main__':
    main()