# -*- coding: utf-8 -*-
"""07_tiny_mad_lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVh8JgDAvvBRx42SYE7nzr_EXBi-BRFa
"""

def main():

   sentence = "Code in Place is fun. I learned to program and used Python to make my"

   adjective = input("Please type an adjective and press enter: \033[1;3m")
   noun = input("\033[0mPlease type a noun and press enter: \033[1;3m")
   verb = input("\033[0mPlease type a verb and press enter: \033[1;3m")

   print("\033[0m"+sentence + " " + adjective + " " + noun + " " + verb + "!")



if __name__ == '__main__':
    main()