# -*- coding: utf-8 -*-
"""01_fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k5QPNbx_q1BHuFtr54jd3d5fVvR9nT1D
"""

def fibonacci_sequence(max_value):
  a,b = 0,1
  while a < max_value:
    print(a, end=" ")
    a, b = b, a + b

def main():
  Max_Value = 10000
  fibonacci_sequence(Max_Value)


if __name__ == '__main__':
    main()