# -*- coding: utf-8 -*-
"""02_print_events.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dmVJTl-nTlc3GYY7R2PrIuFsZ2HnI5b
"""

def main():


    for i in range(20):
      print(i * 2, end=" ")



if __name__ == '__main__':
    main()