# -*- coding: utf-8 -*-
"""03_wholesome_machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dl_07haZZYhkvz2XqzEqjDB6Kfbm54A6
"""

CBLUE = '\33[34m'
CWHITE = '\33[37m'

affirmation = "I am capable of doing anything I put my mind to."

def main():


   print(f"{CWHITE}Please type the following affirmation: {affirmation}")

   while True:
    user_input = input(f"{CBLUE}")
    if user_input == affirmation:
      print(f"{CWHITE}That's right! :)")
      break
    else:
      print(f"{CWHITE}Hmmm That was not the affirmation. Please try again:")




if __name__ == '__main__':
    main()