# -*- coding: utf-8 -*-
"""00_averages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mh3ZUbJwirFPRpRxA5NEI1_lNGOaXxsn
"""

def average(a: float, b: float):

    sum = a + b
    return sum / 2


def main():

    avg_1 = average(0, 10)
    avg_2 = average(8, 10)

    final = average(avg_1, avg_2)

    print("avg_1:", avg_1)
    print("avg_2:", avg_2)
    print("final:", final)






if __name__ == '__main__':
    main()