# -*- coding: utf-8 -*-
"""01_chaotic_counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tor7cw12De2jKmELIdb9G1Lj4QI7aL6b
"""

import random

DONE_LIKELIHOOD = 0.3

def done():
  return random.random() < DONE_LIKELIHOOD

def chaotic_counting():
  for i in range(1, 11):
    if done():
      return
    print(i, end=" ")

def main():
    print("I'm going to count until 10 or until I feel like stopping, whichever comes first.")
    chaotic_counting()
    print("I'm done.")



if __name__ == '__main__':
    main()