# -*- coding: utf-8 -*-
"""02_count_even.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7POPfLDR9DvymeNs0PWrnEIvoAFaeaz
"""

def main():
    numbers = []

    while True:
      user_input = input("Enter an integer or press enter to stop: ")
      if(user_input  == ""):
        break
      try:
        numbers.append(int(user_input))
      except ValueError:
        print("Please enter a valid integer.")

    even_count = sum(1 for num in numbers if num % 2 == 0)
    print(f"Number of even numbers: {even_count}")




if __name__ == '__main__':
    main()