# -*- coding: utf-8 -*-
"""04_double.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hlXmCUmFJJ_ubIgtuAviSSFyelwFnuc
"""

bold_italic = "\033[1;3m"
reset = "\033[0;0m"

def double(num):
  return num * 2

def main():

  num = int(input(f"Enter a number: {bold_italic}"))

  total = double(num)

  print(f"{reset}{num} Double that is {total}.")




if __name__ == '__main__':
    main()