# -*- coding: utf-8 -*-
"""05_get_name.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TAY1Lo1-83DgAcolkG8oZUSfGcyc-luK
"""

def get_name():
  return "Sophia"

def main():
    name = get_name()

    print(f"Howdy {name}! 🤠")



if __name__ == '__main__':
    main()