# -*- coding: utf-8 -*-
"""09_sentence_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgVqq6I6HmWX6uwjfeuzCBbNDaZNYqHw
"""

CBLUE = '\33[34m'
CWHITE = '\33[37m'

def make_sentence(word, part_of_speech):
    if(part_of_speech == 0):
        print(f"{CWHITE}I am excited to add this {word} to my vast collection of them!")
    elif(part_of_speech == 1):
        print(f"{CWHITE}It's so nice outside today it makes me want to {word}!")
    elif(part_of_speech == 2):
      print(f"{CWHITE}Looking out my window, the sky is big and {word}!")
    else:
        print(f"{CWHITE}Invalid input! Please enter 0 for noun, 1 for verb, or 2 for adjective.")




def main():
    word = input(f"Please type a noun, verb, or adjective: {CBLUE}")
    part_of_speech = int(input(f"{CWHITE}Is this a noun, verb, or adjective? Type 0 for noun, 1 for verb, 2 for adjective: {CBLUE}"))
    make_sentence(word, part_of_speech)



if __name__ == '__main__':
    main()