# -*- coding: utf-8 -*-
"""10_print_ones_digit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wbv0eyEadTXLlLGETKnBdlnjj-n9xMaC
"""

CBLUE = '\33[34m'
CWHITE = '\33[37m'

def print_ones_digit(num):
    ones_digit = num % 10
    print(f"{CWHITE}The ones digit is {ones_digit}")


def main():
    num = int(input(f"Enter a number: {CBLUE}"))
    print_ones_digit(num)



if __name__ == '__main__':
    main()