# -*- coding: utf-8 -*-
"""02_pop_up_shop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GGoulDxB9wxOuMt7E2Rog5mRVnlxffXL
"""

def main():
    fruits = {'apple': 10, 'durian': 5, 'jackfruit': 56, 'kiwi': 100, 'rambutan': 33, 'mango': 1.5}

    total_cost = 0

    for fruit_name in fruits:
        price = fruits[fruit_name]
        try:
            amount_bought = int(input(f"\033[0mHow many ({fruit_name}) do you want to buy?: \033[1;3m"))
            total_cost += (price * amount_bought)
        except ValueError:
            print("\033[0mInvalid input! Please enter a valid number.")


    print(f"\033[0mYour total is ${total_cost}")


if __name__ == '__main__':
    main()